from __future__ import annotations

import json
from pathlib import Path
from datetime import datetime

from src.core.config import ConfigLoader
from src.trainers import TrainerFactory


class TrainingOrchestrator:
    """
    High-level orchestrator that:
        ✓ Loads YAML config
        ✓ Iterates over folds generated by KFoldDatasetPipeline
        ✓ Dynamically instantiates the selected trainer
        ✓ Runs training for each fold
        ✓ Saves results in a structured experiment directory

    Output structure:
        experiments/
            model_name/
                run_YYYYMMDD_HHMMSS/
                    fold_01/
                        train.json
                        val.json
                        checkpoints/
                        metrics.json
                    fold_02/
                    summary.json
    """

    def __init__(self, config_path: Path):
        self.config_loader = ConfigLoader(config_path=config_path)

        # load sections
        self.training_cfg = self.config_loader.load_training()
        self.model_cfg = self.config_loader.load_model()
        self.dataset_cfg = self.config_loader.load_canonical()

        # folds metadata
        canonical_output = self.dataset_cfg["canonical"]["output_dir"]
        folds_root = Path(canonical_output) / "kfolds"

        self.folds_metadata = json.load(open(folds_root / "metadata.json"))
        self.folds_root = folds_root

        # experiment root
        model_name = self.model_cfg["model"]["name"]
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        self.exp_root = Path("experiments") / model_name / f"run_{timestamp}"
        self.exp_root.mkdir(parents=True, exist_ok=True)

        print(f"\n📁 Experiment root: {self.exp_root}")

        # choose trainer dynamically
        self.trainer_class = TrainerFactory.get_trainer(self.model_cfg["model"]["name"])

    # -------------------------------------------------------------------------
    def run(self):

        folds_results = []

        print("\n🚀 Starting Training Orchestrator")
        print(f"Model: {self.model_cfg['model']['name']}")
        print(f"Folds directory: {self.folds_root}")

        # iterate over all folds
        for fold_info in self.folds_metadata["folds"]:

            fold_id = fold_info["fold"]
            fold_dir = self.exp_root / f"fold_{fold_id:02d}"
            fold_dir.mkdir(exist_ok=True)

            print(f"\n===================================")
            print(f"Training Fold {fold_id}")
            print(f"===================================")

            # dataset paths
            train_json = fold_info["train_json"]
            val_json = fold_info["val_json"]

            # instantiate trainer
            trainer = self.trainer_class(
                training_cfg=self.training_cfg,
                model_cfg=self.model_cfg,
                fold_dir=fold_dir,
                train_json=train_json,
                val_json=val_json,
            )

            # run training
            metrics = trainer.run()

            # save metrics summary for this fold
            json.dump(
                metrics,
                open(fold_dir / "metrics.json", "w"),
                indent=2
            )

            folds_results.append({
                "fold": fold_id,
                **metrics
            })

        # ------------------------------------------------------------------
        # FINAL SUMMARY
        # ------------------------------------------------------------------
        summary_path = self.exp_root / "summary.json"
        json.dump(
            {
                "model": self.model_cfg["model"]["name"],
                "created_at": datetime.now().isoformat(),
                "num_folds": self.folds_metadata["num_folds"],
                "folds": folds_results
            },
            open(summary_path, "w"),
            indent=2
        )

        print("\n🎉 TRAINING COMPLETE!")
        print(f"📄 Summary saved at: {summary_path}")

        return summary_path
