alias_map:

  planktonic_foraminifer:
    - planctonico
    - planctônico
    - plancton
    - planktonic foraminifer

  benthic_foraminifer:
    - bentonico
    - bentônico
    - benthonico
    - benthic foraminifer

  ostracod:
    - ostracoda
    - ostracode
    - ostracod

  gastropod:
    - gastropoda
    - gastrópode
    - gastropode
    - gastropod

  bivalve:
    - bivalvia
    - bivalve
    - bivalves

  scaphopod:
    - scaphopoda
    - escafopode
    - scaphopod

  echinoid_spine:
    - echinoidea
    - equinoidea
    - echinoid spine

  bryozoan:
    - bryozoa
    - briozoa
    - bioconstrutor
    - bio-construtor
    - bryozoan

  microfossil_fragment:
    - fragmento de microfossil
    - fragmento de microfóssil
    - fragmento microfossil
    - fragmento microfóssil
    - crustacea
    - crustaceo
    - crustáceo
    - crustaceos
    - crustáceos

  miscellaneous:
    - microfossil desconhecido
    - microfóssil desconhecido
    - fossil desconhecido
    - microfossil indiferenciado
    - microfóssil indiferenciado
    - fossil indiferenciado
    - dente
    - dentes
    - tooth
    - porifera
    - porífero
    - diatomacea
    - diatomaceas
    - diatomácea
    - diatomáceas
    - charophyta